projectName: GMBT Example for Gothic 2

minimalVersion: v0.15

gothicRoot: ..\..\..

modFiles:
  assets:
    - mdk
    - mod
    - thirdparty

  defaultWorld: TOTENINSEL.ZEN

modVdf:
  output:  ..\..\..\Data\ModVDF\GMBT_Example_Project.mod
  comment: Gothic Mod Build Tool - Example Project
